name: http_in_memory_web_api
description: A starting point for Dart libraries or applications.
version: 0.0.1
author: Adao Junior <itsjunnior@gmail.com>
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  http: '^0.11.3+3'
  browser: '^0.10.0+2'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
