name: http_in_memory_web_api
description: An in-memory web api for demos and tests.
version: 0.1.0
author: Adao Junior <itsjunnior@gmail.com>
homepage: https://github.com/adaojunior/http-in-memory-web-api
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  http: '^0.11.3+3'
  browser: '^0.10.0+2'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
